# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.updateTable = QtWidgets.QPushButton(self.centralwidget)
        self.updateTable.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateTable.setMouseTracking(True)
        self.updateTable.setObjectName("updateTable")
        self.verticalLayout.addWidget(self.updateTable)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.goTest = QtWidgets.QPushButton(self.centralwidget)
        self.goTest.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goTest.setMouseTracking(True)
        self.goTest.setObjectName("goTest")
        self.verticalLayout.addWidget(self.goTest)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Твои ответы влияют на сформированный алгоритм"))
        self.comboBox.setItemText(0, _translate("MainWindow", "age"))
        self.comboBox.setItemText(1, _translate("MainWindow", "name"))
        self.comboBox.setItemText(2, _translate("MainWindow", "nation"))
        self.comboBox.setItemText(3, _translate("MainWindow", "univer"))
        self.comboBox.setItemText(4, _translate("MainWindow", "school"))
        self.comboBox.setItemText(5, _translate("MainWindow", "operand"))
        self.updateTable.setText(_translate("MainWindow", "Изменить таблицу"))
        self.pushButton.setText(_translate("MainWindow", "Все таблицы"))
        self.goTest.setText(_translate("MainWindow", "Пройти тест"))
